### ISSUE TITLE
Documenting use of OTF2 Traces for Ember

### ISSUE THREAD

**Issue by deanchester** [sstsimulator/sst-docs#15]
I have written some documentation for the use of the OTF2 trace motif in Ember, it covers capturing the OTF2 traces with TAU and then which file to tell the motif to look at.

Can you let me know where you want that to reside and I'll issue a PR with the new documentation.

**Comment by gvoskuilen** [comment]
You can put the file(s) in docs/elements/ember/. And then add the filename to website/sidebars.js right after the current files in the ember directory. Thanks!
